name: SFTP Interface Integration Test
on:
  push:
    branches: [ main ]
jobs:
  setup-python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    env:
      PYTHON_VERSION: 3.9
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest requests lxml paramiko cryptography
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
